### ISSUE TITLE
Update all services in dev env to their latest state

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/NoOps#107]
AS A Product Owner
I WANT TO have all services in dev environment to be updated to their latest state
SO THAT I could test them

### Acceptance Criteria

> This is a temporary, one-time task to make sure that `dev` environment is up-to-date. Currently, it seems that after replacing `play` with `dev`, some of the latest bug fixes and feature developments are missing.

- [x] Use GitHub Secrets as source for Docker Compose values
- [x] All of the services in scope are updated to their latest state based on their ~`main`~ `dev` branch and their `Docker Compose`
- [ ] ~Error messages are grepped per every component and made sure that no DSL is missing or reporting with an error~

#### Scope

- [x] buerokratt/NoOps#86
- [x] buerokratt/NoOps#87
- [x] buerokratt/NoOps#88
- [x] buerokratt/NoOps#89
- [x] buerokratt/NoOps#90
