### ISSUE TITLE
Apply external variables on deploy pipelines

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/NoOps#113]
AS AN Architect
I WANT to make sure that on deployment, sensitive and client-specific variables are fetched from an external source
SO THAT default variables could be used in scripts in order to deploy them locally

AS A DevOps
I WANT to make sure that on deployment, sensitive and client-specific variables are fetched from an external source
SO THAT default variables could be overwritten with client-specific ones

### Acceptance Criteria

> In scope of this task, by `modules` we mean Training Module, Service Module, etc.

- [ ] All modules must be deployable separately
- [ ] All modules must be deployable in combination with others

#### Deployment

- [ ] All Bürokratt's `components` must be deployed before deploying `modules`
- [ ] _Before deploying Bürokratt `modules`, validate if all necessary `components` have been deployed_ [lowest priority]
- [ ] Use separate `Docker images` for module's GUI
- [ ] Use separate `Docker images` for module's DSLs

#### Scope of this issue

- [ ] All modules-related DSLs come from https://github.com/buerokratt/Buerokratt-DSL
- [ ] Deployment on Kubernetes
- [ ] Deployment on Docker

#### Repositories

- [ ] https://github.com/buerokratt/NoOps/tree/dev/Kubernetes for ongoing developments
- [ ] https://github.com/buerokratt/NoOps/tree/main/Kubernetes for production-ready solutions
- [ ] https://github.com/buerokratt/NoOps/tree/dev/Kubernetes/Components for Bükstack components
- [ ] https://github.com/buerokratt/NoOps/tree/dev/Kubernetes/Modules for Bürokratt's modules
- [ ] Use https://github.com/buerokratt/buerokratt-helm/tree/dev as a reference
- [ ] Use https://github.com/buerokratt/NoOps/tree/dev/Kubernetes as a reference

#### Kubernetes-based deployment

- [x] #115
- [ ] #114
- [x] #122
- [ ] If Script `deploy kube` is called with no selections passed then all components and modules have to be deployed to the latest changes
