### ISSUE TITLE
Automated pipelines to create and manipulate database schemas

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/NoOps#175]
AS AN Architect
I WANT automated pipelines to be used to create and manipulate database schemas
SO THAT these processes could be repeated in all environments

### Acceptance Criteria

- [ ] [Liquibase](https://www.liquibase.com) is used as an automation tool
- [ ] [YAML format](https://docs.liquibase.com/concepts/changelogs/yaml-format.html) is used for Liquibase Changlelogs
- [ ] Liquibase pipeline has to cover all required database manipulation-related functionalities
