### ISSUE TITLE
Turvis implementation

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/NoOps#176]
AS A SecOps
I WANT Turvis to be implemented
SO THAT I could apply custom security rules

### Acceptance Criteria

- [ ] [Turvis](https://github.com/buerokratt/Turvis) is implemented and fully functional on all Bürokratt's environments (`dev`, `test`, `stage`, `prod`)
- [ ] Deployment based on [Bürokratt's NoOps](https://github.com/buerokratt/NoOps) principles
> See [Modules deployment via Helm Charts](https://github.com/buerokratt/NoOps/tree/dev/Kubernetes/Modules) as an example

#### Scope

- [ ] Creating Bürokratt-specific Turvis DSLs is out of scope of this issue
- [ ] Fixing potentially flawed functionalities of current version of Turvis is out of scope of this issue
- [ ] Resolving potentially poor code quality _(code smells, code duplication, bad practices, etc.)_ reported by [Sonarcloud.io](https://sonarcloud.io) of current version of Turvis is out of scope of this issue
- [ ] Upgrading Turvis's dependencies to remove security issues reported by [Snyk.io](https://snyk.io) of current version of Turvis is within scope of this issue
