### ISSUE TITLE
Implement automated pipeline for code commits

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/NoOps#207]
AS AN Architect
I WANT TO implement automated pipeline for code commits
SO THAT this flow would be without manual intervention and maintains clear versioning and change tracking

### Acceptance Criteria

- [ ] GitHub Actions applied on all applicable repositories
- [ ] Automatic validation of committed code
- [ ] Code versioning is based on [Semantic Versioning](https://semver.org)
- [ ] Any branches other than short-lived `feature` branches currently in use, `dev`, `test`, `stage`, and `main`, are deleted
- [ ] #212

#### Branches

- [ ] Short-lived `feature` branches for daily developments
- [ ] `dev` branch as a merger of `feature` branches
- [ ] `test` branch for code that has passed automated testing in `dev` branch
- [ ] `stage` branch for code that has passed extensive testing in `test` branch
- [ ] `main` branch for code that has passed all tests in `stage` branch

#### Versioning

- [ ] All commits to branches other than short-lived feature branches will be automatically versioned in a format of `major`.`minor`.`patch`

##### Transition of `patch` versions

- [ ] Patches introduced in `dev` (e.g., `v1.2.1`) are preserved through all branches (`test`, `stage`, `main`)

##### Incrementing `minor` versions

- [ ] New `minor` versions can only be introduced in `dev` branch

##### Incrementing `major` versions

- [ ] New `major` versions can only be introduced in `major` branch

#### Commit Message Validation

- [ ] All commit messages must follow the Conventional Commits standard, with the format `[type(scope): description]`
> [!NOTE]
> E.g., `[type(scope): description]` => `[feat(207): Implement automated pipeline for code commits]`
- [ ] The acceptable commit types are `feat`, `fix`, `chore`, `docs`, `refactor`, `style`, and `test`
- [ ] Commit messages that do not adhere to the specified format are rejected automatically

#### Automated Release History Generation

- [ ] Each successful merge from `dev` to `test`, `test` to `stage`, and `stage` to `main`, should trigger automatic generation of a release history (changelog)
- [ ] The release history should be grouped by commit types (e.g., `feat`, `fix`), and display a summary of changes in the format `CHANGELOG.md`
- [ ] The release history file is automatically updated and committed on each merge to a major branch (`test`, `stage`, `main`)
- [ ] Release tags are automatically created for each new version, aligning with semantic versioning rules

**Comment by varmoh** [comment]
PR
https://github.com/buerokratt/pipelines-automation/pull/12

**Comment by rasmusei** [comment]
Unable to Implement automated pipeline for some repos at the moment. Blocked by subtask

**Comment by jaX10bt** [comment]
After discussion with @1AhmedYasser, @varmoh, @jaX10bt:

- remove CHANGELOG.md from all branches except main
- add a check to generate CHANGELOG.md only when merging to main
