### ISSUE TITLE
Bürokratt as SaaS at Riigipilv on Kubernetes

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/NoOps#33]
AS A Product Owner
I WANT any public sector clients to be able to start using Bürokratt as SaaS in Riigipilv
SO THAT their onboarding would always follow the same procedures and be technically automated as much as possible

### Acceptance Criteria

General
- [ ] #34
- [ ] Technical deployment on Kubernetes
- [ ] Deploy default Chat Widget on a blank page for every Client
- [ ] Penetration tests
- [ ] Initial bot, created by RIA for the client, is available
- [ ] Training is working in Bürokratt when using Kubernetes
- [ ] Use optimal resources regarding Bürokratt infrastructure

Pipelines
- [ ] Deploy initial client-specific Rasa model _(from private GitHub repo)_

**Comment by turnerrainer** [comment]
Initial remote demo done based on https://github.com/Fronox/buerokratt-helm.

On track.

**Comment by turnerrainer** [comment]
Rasa added to Helm Chart on 21.03.2022

**Comment by turnerrainer** [comment]
TARA authentication is currently not implemented due to business reasons.

Also, v1 / MVP is currently deployed but will be replaced with v2.

Back-end pipelines are working but marked as "Blocked" as needs modifications until ready for prod.
