### ISSUE TITLE
TTJA environment fixes

### ISSUE THREAD

**Issue by KlviG** [buerokratt/NoOps#51]
AS AN Customer support agent
I WANT TO receive visual and sound indicator in my workplace network, when new message comes from client
SO THAT i could react to messages faster

### Acceptance Testing

- [ ] Fix notification sound/visuals
- [x] Fix network accessibility
- [ ] Messages aren't always received

**Comment by KlviG** [comment]
For network fix, need to contact with TTJA back end service provider

**Comment by KlviG** [comment]
Network accessibility was most likely caused by temporary moving of TTJA office.
Notifification error includes STAT end aswell
