### ISSUE TITLE
Bürokratt `dev` deployment pipeline to Riigipilv based on GitHub Actions

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/NoOps#63]
AS AN Architect
I WANT the whole process of Bürokratt deployment to Riigipilv to be fully automated and based on GitHub Actions
SO THAT I could be confident that the same problems would only be solved once and consistently applied in the same way

#### Related epics

- [x] #80

#### Triggers

> Triggers will be a part of deployment scripts

#### Deployment of base components

> The following components are installed as bare components without any Bürokratt-specific configuration

##### Bükstack

- [x] #100
- [x] #72
- [x] #73
- [x] #71
- [ ] ~#74~
- [ ] ~#75~
- [ ] ~#76~
- [x] #77

##### Third-party components

- [ ] #101
- [ ] #102
- [ ] #103

#### Deployment of Bürokratt services

> Epic of these sub-issues
> #104

- [ ] Deploy Bürokratt-specific DSLs of Administrative Tool
- [ ] Deploy Bürokratt-specific DSLs of Chat Widget
- [x] Deploy Bürokratt-specific DSLs of Training Module
- [x] Deploy Bürokratt-specific DSLs of Services
- [ ] ~Deploy Bürokratt-specific DSLs of Turvis~

#### External file storage

- [ ] #64
- [ ] #65
- [ ] #66
- [ ] #67

#### Secure connections

- [ ] #68
- [ ] #69

#### Monitoring

- [ ] ~Publish application logs for debugging purposes in Dev~

#### Environments

- [x] Set up a fully automated deployment pipeline for Bürokratt `dev`
- [ ] ~Set up a fully automated deployment pipeline for Bürokratt `test`~
- [ ] ~Set up a fully automated deployment pipeline for Bürokratt `stage`~
- [ ] ~Set up a fully automated deployment pipeline for Bürokratt `demo`~

#### New clients onboarding

**Comment by turnerrainer** [comment]
Consider done as the epic is too wide and the setup is already there.
