### ISSUE TITLE
Bürokratt DEV deployment pipeline

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/NoOps#80]
AS AN Architect
I WANT `dev` environment to be constantly evolving based on the development's actual current state
SO THAT I could be confident that the process of development and deployment follows the defined criteria

AS A DevOps
I WANT `dev` environment to be constantly evolving based on the development's actual current state
SO THAT the process of deployment follows the defined criteria and would usually not require any manual work

AS A Developer
I WANT `dev` environment to be constantly evolving based on the development's actual current state
SO THAT my latest developments could be tested right after I deploy them

#### GitHub Actions

- [x] Triggers based on GitHub Actions

#### Integration of new code

- [x] The `dev` branch of a component/service is used as a source
- [x] Build the new version of software locally based on the source code
- [x] Only launching a `Docker Compose` is allowed
- [ ] ~Manual changes to launch the service are not allowed~

**Comment by turnerrainer** [comment]
Continues enhancements based on specific tasks. Done in general - `dev` environment is being built and deployed based on `dev` branch using changing the software version as trigger for fully automated CI/CD pipeline.
